# Generated by Django 4.2 on 2025-11-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='site_video',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
